### ISSUE TITLE
gradle :pwt:javadoc failed on Mac OS X

### ISSUE THREAD

**Issue by stbland** [Putnami/putnami-web-toolkit#115]
The command gradle :pwt:javadoc failed on Mac OS X ( Gradle 2.2.1, JVM: 1.8 ) : 

...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/error/client/ErrorHandler.java:62: warning: empty <p> tag
         * </p>
           ^
...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/error/client/ErrorHandler.java:29: error: unexpected end tag: </p>
 * </p>
   ^
...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/error/client/ErrorHandler.java:46: error: unexpected end tag: </p>
 * </p>
   ^
...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/error/client/ErrorManager.java:38: error: unexpected end tag: </p>
 * </p>
   ^
...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/widget/client/base/AbstractForm.java:171: warning: no @return
        public boolean hasError() {
                       ^
...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/theme/client/DefaultThemeController.java:26: error: self-closing element not allowed
 * The DefaultThemeController is the default {@link ThemeController} implemenation. <br/>
                                                                                    ^
...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/theme/client/DefaultThemeController.java:33: error: bad use of '>'
 * <li>Remove all the css in the &lt;head> tag</li>
                                         ^
...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/theme/client/ThemeController.java:31: error: bad use of '>'
 * &lt;replace-with class="you.package.CustomThemeController">
                                                             ^
...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/theme/client/ThemeController.java:32: error: bad use of '>'
 *      &lt;when-type-is class="fr.putnami.pwt.core.theme.client.ThemeController"/>
                                                                                  ^
...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/theme/client/ThemeController.java:33: error: bad use of '>'
 * &lt;/replace-with>
                    ^
...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/mvp/client/ViewPlace.java:56: warning: no description for @param
         * @param token
           ^
...putnami-pwt/core/src/main/java/fr/putnami/pwt/core/inject/client/annotation/MvpDescription.java:44: error: unknown tag: ActivityFactory
         * GWT.<ActivityFactory> create(class)
               ^
9 errors
3 warnings

**Comment by stbland** [comment]
I try with last Gradle version (2.3) on Mac OS X : I obtain the same errors

**Comment by stbland** [comment]
I try with last Gradle version (2.3) on Windows : It succeed.

The only two differences are JDK and operating system ?!

**Comment by fdumay** [comment]
PWT doesn’t compile under JDK 1.8. I will work on it when GWT 2.8 will be released.

**Comment by stbland** [comment]
The javadoc command comming with JDK 1.8 is too strict ( DocLint feature ). There is a solution to this problem with Maven (http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete) and with Gradle ( http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html )

**Comment by fdumay** [comment]
The javadoc is maybe too strict on java 1.8, but I think is a good thing, we will fix it soon
